//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lingya.Xpf.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lingya.Xpf.Localization.ViewResources", typeof(ViewResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string Command_Add {
            get {
                return ResourceManager.GetString("Command_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核 的本地化字符串。
        /// </summary>
        public static string Command_Audit {
            get {
                return ResourceManager.GetString("Command_Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核全部 的本地化字符串。
        /// </summary>
        public static string Command_AuditAll {
            get {
                return ResourceManager.GetString("Command_AuditAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消审核 的本地化字符串。
        /// </summary>
        public static string Command_CancelAudit {
            get {
                return ResourceManager.GetString("Command_CancelAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Command_Close {
            get {
                return ResourceManager.GetString("Command_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量: {0} 的本地化字符串。
        /// </summary>
        public static string Command_Count {
            get {
                return ResourceManager.GetString("Command_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定制 的本地化字符串。
        /// </summary>
        public static string Command_CustomizeLayout {
            get {
                return ResourceManager.GetString("Command_CustomizeLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Command_Delete {
            get {
                return ResourceManager.GetString("Command_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Command_Edit {
            get {
                return ResourceManager.GetString("Command_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出... 的本地化字符串。
        /// </summary>
        public static string Command_Export {
            get {
                return ResourceManager.GetString("Command_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        public static string Command_New {
            get {
                return ResourceManager.GetString("Command_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Command_Refresh {
            get {
                return ResourceManager.GetString("Command_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表 的本地化字符串。
        /// </summary>
        public static string Command_Reports {
            get {
                return ResourceManager.GetString("Command_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置/归零 的本地化字符串。
        /// </summary>
        public static string Command_Reset {
            get {
                return ResourceManager.GetString("Command_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置布局 的本地化字符串。
        /// </summary>
        public static string Command_ResetLayout {
            get {
                return ResourceManager.GetString("Command_ResetLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Command_Save {
            get {
                return ResourceManager.GetString("Command_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存全部 的本地化字符串。
        /// </summary>
        public static string Command_SaveAll {
            get {
                return ResourceManager.GetString("Command_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存并关闭 的本地化字符串。
        /// </summary>
        public static string Command_SaveAndClose {
            get {
                return ResourceManager.GetString("Command_SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存并新建 的本地化字符串。
        /// </summary>
        public static string Command_SaveAndNew {
            get {
                return ResourceManager.GetString("Command_SaveAndNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存布局 的本地化字符串。
        /// </summary>
        public static string Command_SaveLayout {
            get {
                return ResourceManager.GetString("Command_SaveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导航 的本地化字符串。
        /// </summary>
        public static string LayoutPanel_Navigation {
            get {
                return ResourceManager.GetString("LayoutPanel_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 的本地化字符串。
        /// </summary>
        public static string RibbonPage_Home {
            get {
                return ResourceManager.GetString("RibbonPage_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视图 的本地化字符串。
        /// </summary>
        public static string RibbonPage_View {
            get {
                return ResourceManager.GetString("RibbonPage_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外观 的本地化字符串。
        /// </summary>
        public static string RibbonPageGroup_Appearance {
            get {
                return ResourceManager.GetString("RibbonPageGroup_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核操作 的本地化字符串。
        /// </summary>
        public static string RibbonPageGroup_Audit {
            get {
                return ResourceManager.GetString("RibbonPageGroup_Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string RibbonPageGroup_Edit {
            get {
                return ResourceManager.GetString("RibbonPageGroup_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 布局 的本地化字符串。
        /// </summary>
        public static string RibbonPageGroup_Layout {
            get {
                return ResourceManager.GetString("RibbonPageGroup_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string RibbonPageGroup_Operation {
            get {
                return ResourceManager.GetString("RibbonPageGroup_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 任务 的本地化字符串。
        /// </summary>
        public static string RibbonPageGroup_Tasks {
            get {
                return ResourceManager.GetString("RibbonPageGroup_Tasks", resourceCulture);
            }
        }
    }
}
